const pool = require('../config/db');

exports.ListePlaces = () => {

    let ListeLieu = [
        'cavapizza',
        'tokyoburger',
        'mcdonaldsComedie',
        'leclocher',
        'laopportunite',
        'chezjeremie',
        'lepetitvieux',
        'lestroispoissons',
        'lestroisptitscochons',
        "l'atelierdesvins",
        'lestroiscuisines',
        'aucoeurdelamour',
        'restaurationlagrande',
        'lefrancais',
        'lebanian',
        'lafontaine',
        "l'arome",
        'lalune',
        'lemediterraneen',
        'ledomaine',
        'lebijou',
        'lecharpentier',
        'lemarocain',
        'laupieddecane',
        'lascoutade',
        'lacuisineparisienne',
        'legosier',
        'lamedina',
        'lechefsouslesetoiles',
        'lapoissondansletoit',
        'lecoqchic',
        'lepainmolle',
        'laplanche',
        'lepotagerdelamarguerite',
        'lecompte',
        'latablemontpellier',
        'laforgeron',
        'lenormand',
        'latraversee',
        'lesbistrots',
        'lesconfidences',
        'lajoie',
        'lebourbon',
        'laveilleville',
        "l'atelierargentin",
        'lavillegreen',
        'lestartle',
        'lecampanile',
        'lacaille',
        'laferme',
        'labrasserie',
        'laluneblanche',
    ];

    return ListeLieu;

};