name: Build and Deploy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install dependencies
        working-directory: m_trotter
        run: flutter pub get

      - name: Debug secrets (safe)
        run: |
          echo "KEYSTORE path: ${{ secrets.MYAPP_KEYSTORE_B64 != '' && 'OK' || 'MISSING' }}"
          echo "KEY PASSWORD: ${{ secrets.MYAPP_KEY_PASSWORD != '' && 'OK' || 'MISSING' }}"
          echo "STORE PASSWORD: ${{ secrets.MYAPP_STORE_PASSWORD != '' && 'OK' || 'MISSING' }}"
          echo "KEY ALIAS: ${{ secrets.MYAPP_KEY_ALIAS != '' && 'OK' || 'MISSING' }}"
          echo "SERVER_URL: ${{ secrets.SERVER_URL != '' && 'OK' || 'MISSING' }}"   

      - name: Decode keystore
        working-directory: m_trotter
        run: |
          echo "${{ secrets.MYAPP_KEYSTORE_B64 }}" | base64 --decode > android/app/keystore.jks

      - name: Generate gradle.properties
        working-directory: m_trotter/android
        run: |
          cat <<EOF > gradle.properties
          org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
          android.useAndroidX=true
          android.enableJetifier=true
          MYAPP_KEYSTORE=android/app/keystore.jks
          MYAPP_KEY_ALIAS=mtrotter
          MYAPP_KEY_PASSWORD=${{ secrets.MYAPP_KEY_PASSWORD }}
          MYAPP_STORE_PASSWORD=${{ secrets.MYAPP_STORE_PASSWORD }}
          EOF

      - name: Build APK (release)
        working-directory: m_trotter
        run: flutter build apk --dart-define=SERVER_URL=http://217.182.79.84:3000

      - name: Upload via SSH to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          source: m_trotter/build/app/outputs/flutter-apk/app-release.apk
          target: /var/www/html/apk
