name: Build and Deploy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Verify project structure
        run: |
          ls -la m_trotter/
          echo "Checking if android directory exists:"
          if [ -d "m_trotter/android" ]; then
            echo "Directory exists"
            ls -la m_trotter/android/
          else
            echo "Directory does not exist"
            echo "Project structure:"
            find m_trotter -type d | sort
          fi
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
      
      - name: Install dependencies
        working-directory: m_trotter
        run: flutter pub get
      
      - name: Create and configure gradle.properties
        working-directory: m_trotter/android
        run: |
          # Créer le fichier avec les configurations AndroidX
          cat > gradle.properties <<EOL
          org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
          android.useAndroidX=true
          android.enableJetifier=true
          
          # Secrets pour la signature
          MYAPP_KEYSTORE_B64=${{ secrets.MYAPP_KEYSTORE_B64 }}
          MYAPP_KEY_ALIAS=${{ secrets.MYAPP_KEY_ALIAS }}
          MYAPP_KEY_PASSWORD=${{ secrets.MYAPP_KEY_PASSWORD }}
          MYAPP_STORE_PASSWORD=${{ secrets.MYAPP_STORE_PASSWORD }}
          EOL
          
          # Afficher le contenu pour vérification
          cat gradle.properties
      
      - name: Decode keystore
        run: echo "${{ secrets.MYAPP_KEYSTORE_B64 }}" | base64 --decode > /tmp/keystore.jks
      
      - name: Build APK (release)
        working-directory: m_trotter
        run: flutter build apk --release --dart-define=SERVER_URL=http://217.182.79.84:3000
        env:
          MYAPP_KEY_PATH: /tmp/keystore.jks
          MYAPP_KEY_ALIAS: ${{ secrets.MYAPP_KEY_ALIAS }}
          MYAPP_KEY_PASSWORD: ${{ secrets.MYAPP_KEY_PASSWORD }}
          MYAPP_STORE_PASSWORD: ${{ secrets.MYAPP_STORE_PASSWORD }}
        
      - name: Upload via SSH to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          source: m_trotter/build/app/outputs/flutter-apk/app-release.apk
          target: /var/www/html/apk