name: Build and Deploy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install dependencies
        working-directory: m_trotter
        run: flutter pub get

      - name: Decode keystore
        working-directory: m_trotter
        run: |
          echo "${{ secrets.MYAPP_KEYSTORE_B64 }}" | base64 --decode > android/app/keystore.jks

      - name: Build APK (release)
        working-directory: m_trotter
        run: flutter build apk --dart-define=SERVER_URL=http://217.182.79.84:3000

      - name: Upload via SSH to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          source: m_trotter/build/app/outputs/flutter-apk/app-release.apk
          target: /var/www/html/apk
