name: Build and Deploy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install dependencies
        working-directory: m_trotter
        run: flutter pub get

      - name: Create and configure gradle.properties
        working-directory: m_trotter/android
        run: |
          cat > gradle.properties <<EOL
          org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
          android.useAndroidX=true
          android.enableJetifier=true
          
          MYAPP_KEYSTORE_B64=${{ secrets.MYAPP_KEYSTORE_B64 }}
          MYAPP_KEY_ALIAS=${{ secrets.MYAPP_KEY_ALIAS }}
          MYAPP_KEY_PASSWORD=${{ secrets.MYAPP_KEY_PASSWORD }}
          MYAPP_STORE_PASSWORD=${{ secrets.MYAPP_STORE_PASSWORD }}
          EOL

      - name: Decode keystore
        run: echo "${{ secrets.MYAPP_KEYSTORE_B64 }}" | base64 --decode > /tmp/keystore.jks
        
      - name: Build APK (release)
        working-directory: m_trotter
        run: flutter build apk --dart-define=SERVER_URL=http://217.182.79.84:3000
        env:
          MYAPP_KEY_PATH: /tmp/keystore.jks
          MYAPP_KEY_ALIAS: ${{ secrets.MYAPP_KEY_ALIAS }}
          MYAPP_KEY_PASSWORD: ${{ secrets.MYAPP_KEY_PASSWORD }}
          MYAPP_STORE_PASSWORD: ${{ secrets.MYAPP_STORE_PASSWORD }}
        

      - name: Upload via SSH to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          source: app-release.apk
          target: /var/www/html/apk
